//! Database driver with connection pooling, transactions, and query execution.
//!
//! This crate provides the sqlx-based database layer for Oxyde. It manages connection
//! pools, transactions, and executes SQL generated by oxyde-query.
//!
//! # Architecture
//!
//! ```text
//! SQL + Values → bind parameters → execute via sqlx → rows → JSON/MessagePack
//! ```
//!
//! ## Global Registries
//!
//! - `ConnectionRegistry`: Named pools (e.g., "default", "analytics")
//! - `TransactionRegistry`: Active transactions by tx_id
//!
//! Both are `OnceCell<T>` statics for safe concurrent access.
//!
//! # Pool Management
//!
//! ```rust,ignore
//! init_pool("default", "postgresql://...", settings).await?;
//! init_pool("analytics", "postgresql://...", settings).await?;
//! close_pool("analytics").await?;
//! close_all_pools().await?;
//! ```
//!
//! # Query Execution
//!
//! ```rust,ignore
//! // Outside transaction (with optional type hints for faster decoding)
//! let rows = execute_query("default", sql, values, col_types.as_ref()).await?;
//!
//! // Inside transaction
//! let rows = execute_in_transaction(tx_id, sql, values).await?;
//! ```
//!
//! # Transaction API
//!
//! ```rust,ignore
//! let tx_id = begin_transaction("default").await?;
//! execute_in_transaction(tx_id, sql1, values1).await?;
//! execute_in_transaction(tx_id, sql2, values2).await?;
//! commit_transaction(tx_id).await?;  // or rollback_transaction(tx_id)
//! ```
//!
//! # Validation Strategy
//!
//! - **Input (Python → Rust → DB)**: Data validated in Python via Pydantic v2.
//!   Rust trusts the data and executes SQL without re-validation.
//!
//! - **Output (DB → Rust → Python)**: Rows validated in oxyde-core-py via
//!   pydantic-core validators registered from Python.
//!
//! # Database Support
//!
//! - **PostgreSQL**: Full support (pools, transactions, RETURNING, FOR UPDATE)
//! - **SQLite**: Full support (WAL mode, PRAGMAs, RETURNING 3.35+)
//! - **MySQL**: Full support (pools, transactions, no RETURNING)
//!
//! # SQLite PRAGMAs
//!
//! Applied via `after_connect` hook:
//! - `journal_mode=WAL` (10-20x faster concurrent writes)
//! - `synchronous=NORMAL` (balance speed/safety)
//! - `cache_size=10000` (~10MB cache)
//! - `busy_timeout=5000` (5s lock wait)

use once_cell::sync::OnceCell;
use tracing::info;

// Module declarations
mod error;
mod execute;
mod pool;
mod settings;
mod transaction;

pub mod backend;
mod bind;
mod convert;
mod explain;

// ── Global registries ──────────────────────────────────────────────────────

use pool::ConnectionRegistry;
use transaction::TransactionRegistry;

static REGISTRY: OnceCell<ConnectionRegistry> = OnceCell::new();
static TRANSACTION_REGISTRY: OnceCell<TransactionRegistry> = OnceCell::new();
static CLEANUP_TASK: OnceCell<tokio::sync::Mutex<Option<tokio::task::JoinHandle<()>>>> =
    OnceCell::new();

pub(crate) fn registry() -> &'static ConnectionRegistry {
    REGISTRY.get_or_init(ConnectionRegistry::new)
}

pub(crate) fn transaction_registry() -> &'static TransactionRegistry {
    TRANSACTION_REGISTRY.get_or_init(TransactionRegistry::new)
}

pub(crate) fn ensure_cleanup_task() {
    let task_mutex = CLEANUP_TASK.get_or_init(|| tokio::sync::Mutex::new(None));

    tokio::spawn(async move {
        let mut guard = task_mutex.lock().await;

        // Check if already running
        if let Some(handle) = guard.as_ref() {
            if !handle.is_finished() {
                return;
            }
        }

        // Start new cleanup task
        let handle = tokio::spawn(async {
            loop {
                let interval = transaction_registry().get_cleanup_interval().await;
                tokio::time::sleep(interval).await;

                let removed = transaction_registry().cleanup_stale_transactions().await;
                if removed > 0 {
                    info!(
                        "Cleaned up {} stale transactions (interval: {:?})",
                        removed, interval
                    );
                }
            }
        });

        *guard = Some(handle);
    });
}

// ── Public re-exports (preserves crate API) ────────────────────────────────

// Types
pub use error::{DriverError, Result};
pub use explain::{ExplainFormat, ExplainOptions};
pub use pool::{DatabaseBackend, DbPool};
pub use settings::PoolSettings;

// Pool API
pub use pool::api::{close_all_pools, close_pool, init_pool, init_pool_overwrite, pool_backend};

#[cfg(feature = "pyo3")]
pub use pool::api::get_pool;

// Transaction API
pub use transaction::api::{
    begin_transaction, commit_transaction, create_savepoint, release_savepoint,
    rollback_to_savepoint, rollback_transaction,
};

// Query / statement execution
pub use execute::query::{
    execute_mutation_returning, execute_mutation_returning_in_transaction, execute_query,
    execute_query_columnar, execute_query_columnar_in_transaction, execute_query_in_transaction,
    execute_statement, execute_statement_in_transaction,
};

// INSERT RETURNING
pub use execute::insert::{execute_insert_returning, execute_insert_returning_in_transaction};

// EXPLAIN
pub use explain::explain_query;

// ── Tests ──────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use once_cell::sync::Lazy;
    use sea_query::Value;
    use std::time::Duration;
    use tokio::sync::Mutex as AsyncMutex;

    static TEST_MUTEX: Lazy<AsyncMutex<()>> = Lazy::new(|| AsyncMutex::new(()));

    fn sqlite_settings() -> PoolSettings {
        PoolSettings {
            max_connections: Some(1),
            min_connections: Some(1),
            idle_timeout: None,
            acquire_timeout: Some(Duration::from_secs(5)),
            max_lifetime: None,
            test_before_acquire: Some(false),
            transaction_timeout: None,
            transaction_cleanup_interval: None,
            sqlite_journal_mode: None,
            sqlite_synchronous: None,
            sqlite_cache_size: None,
            sqlite_busy_timeout: None,
        }
    }

    #[tokio::test]
    async fn init_and_close_multiple_pools() {
        let _guard = TEST_MUTEX.lock().await;
        close_all_pools().await.unwrap();

        init_pool("default", "sqlite::memory:", sqlite_settings())
            .await
            .unwrap();
        init_pool("analytics", "sqlite::memory:", sqlite_settings())
            .await
            .unwrap();

        // Simple statement against each pool
        execute_statement("default", "CREATE TABLE foo (id INTEGER)", &[])
            .await
            .unwrap();
        execute_statement("analytics", "CREATE TABLE bar (id INTEGER)", &[])
            .await
            .unwrap();

        // Duplicate name should error
        assert!(matches!(
            init_pool("default", "sqlite::memory:", sqlite_settings()).await,
            Err(DriverError::PoolAlreadyExists(_))
        ));

        close_pool("default").await.unwrap();
        close_pool("analytics").await.unwrap();

        // Closing twice should error
        assert!(matches!(
            close_pool("default").await,
            Err(DriverError::PoolNotFound(_))
        ));
    }

    #[tokio::test]
    async fn execute_with_parameters_sqlite() {
        let _guard = TEST_MUTEX.lock().await;
        close_all_pools().await.unwrap();

        init_pool("default", "sqlite::memory:", sqlite_settings())
            .await
            .unwrap();

        execute_statement(
            "default",
            "CREATE TABLE foo (id INTEGER PRIMARY KEY, name TEXT)",
            &[],
        )
        .await
        .unwrap();

        execute_statement(
            "default",
            "INSERT INTO foo (id, name) VALUES (?, ?)",
            &[Value::from(1_i64), Value::from(String::from("Ada"))],
        )
        .await
        .unwrap();

        let rows = execute_query(
            "default",
            "SELECT name FROM foo WHERE id = ?",
            &[Value::from(1_i64)],
            None,
        )
        .await
        .unwrap();

        assert_eq!(rows.len(), 1);
        assert_eq!(
            rows[0].get("name"),
            Some(&serde_json::Value::String("Ada".to_string()))
        );

        close_pool("default").await.unwrap();
    }

    #[tokio::test]
    async fn transaction_commit_sqlite() {
        let _guard = TEST_MUTEX.lock().await;
        close_all_pools().await.unwrap();

        init_pool("default", "sqlite::memory:", sqlite_settings())
            .await
            .unwrap();

        execute_statement(
            "default",
            "CREATE TABLE foo (id INTEGER PRIMARY KEY, name TEXT)",
            &[],
        )
        .await
        .unwrap();

        let tx_id = begin_transaction("default").await.unwrap();
        execute_statement_in_transaction(
            tx_id,
            "INSERT INTO foo (id, name) VALUES (?, ?)",
            &[Value::from(10_i64), Value::from(String::from("Commit"))],
        )
        .await
        .unwrap();
        commit_transaction(tx_id).await.unwrap();

        let rows = execute_query(
            "default",
            "SELECT name FROM foo WHERE id = ?",
            &[Value::from(10_i64)],
            None,
        )
        .await
        .unwrap();
        assert_eq!(rows.len(), 1);
        assert_eq!(
            rows[0].get("name"),
            Some(&serde_json::Value::String("Commit".to_string()))
        );

        close_pool("default").await.unwrap();
    }

    #[tokio::test]
    async fn transaction_rollback_sqlite() {
        let _guard = TEST_MUTEX.lock().await;
        close_all_pools().await.unwrap();

        init_pool("default", "sqlite::memory:", sqlite_settings())
            .await
            .unwrap();

        execute_statement(
            "default",
            "CREATE TABLE foo (id INTEGER PRIMARY KEY, name TEXT)",
            &[],
        )
        .await
        .unwrap();

        let tx_id = begin_transaction("default").await.unwrap();
        execute_statement_in_transaction(
            tx_id,
            "INSERT INTO foo (id, name) VALUES (?, ?)",
            &[Value::from(11_i64), Value::from(String::from("Rollback"))],
        )
        .await
        .unwrap();
        rollback_transaction(tx_id).await.unwrap();

        let rows = execute_query(
            "default",
            "SELECT name FROM foo WHERE id = ?",
            &[Value::from(11_i64)],
            None,
        )
        .await
        .unwrap();
        assert!(rows.is_empty());

        close_pool("default").await.unwrap();
    }
}
